<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Sparql\Form\SparqlForm $form
 * @var \EasyRdf\Sparql\Result|\EasyRdf\Graph|null $result Unused currently
 * @var array $resultArc2
 * @var string $query
 * @var string $format "text" or "html" Unused currently.
 * @var array $namespaces
 * @var string $errorMessage
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
?>

<?= $this->pageTitle($translate('Sparql'), 1, $translate('Triplestore')) ?>

<?= $this->partial('common/sparql-search') ?>
