language: php

php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - nvm install node
  - nvm use node

install:
  - cd ../..
  - git clone --depth 1 https://github.com/omeka/omeka-s.git
  - cp -a $(readlink -e $(cd -)) omeka-s/modules/Sparql
  - cd omeka-s
  - npm install
  - ./node_modules/gulp/bin/gulp.js init
  - cd modules/Sparql/
  - composer install
  - cd ../..

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_test;" -uroot
  - sed -i 's/^host.*/host = "localhost"/' application/test/config/database.ini
  - sed -i 's/^user.*/user = "root"/' application/test/config/database.ini
  - sed -i 's/^dbname.*/dbname = "omeka_test"/' application/test/config/database.ini
  - cd modules/Sparql/test

script: phpunit
