<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \Sparql\Form\SparqlForm $form
 * @var \EasyRdf\Sparql\Result|\EasyRdf\Graph|null $result Unused currently
 * @var array $resultArc2
 * @var string $query
 * @var string $format "text" or "html"
 * @var array $namespaces
 * @var string $errorMessage
 * @var array $options Passed options from the helper.
 */

// The form uses the format of Omeka / item / search.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->htmlElement('body')->appendAttribute('class', 'sparql');
$this->headLink()->appendStylesheet($this->assetUrl('css/sparql.css', 'Sparql'));

$matches = [];
$pattern = '~^(' . implode('|', array_map('preg_quote', $namespaces)) . ')(.+)$~';
?>

<div class="namespaces">
    <h3><?= $translate('Namespaces') ?></h3>
    <dl>
        <?php foreach ($namespaces as $prefix => $uri): ?>
        <dt><?= $escape($prefix) ?></dt>
        <dd><?= $escape($uri) ?></dd>
        <?php endforeach; ?>
    </dl>
</div>

<?php $submit = $form->get('submit'); ?>
<?php $form->remove('submit'); ?>

<?= $this->form($form) ?>

<div id="page-actions">
    <?= $this->formButton($submit) ?>
</div>

<?php if ($errorMessage): ?>

    <div class='error error-sparql'>
        <h3><?= $escape($translate('Error')) ?></h3>
        <p>
            <?= nl2br($escape($errorMessage)) ?>
        </p>
    </div>

<?php elseif ($resultArc2 && $format === 'text'): ?>

    <div class="result result-text">
        <h3><?= $escape($translate('Results')) ?></h3>
        <table class="tablesaw tablesaw-stack">
            <thead>
                <tr>
                    <?php foreach ($resultArc2['result']['variables'] as $variable): ?>
                    <th><?= $escape($variable) ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($resultArc2['result']['rows'] as $row): ?>
                <tr>
                    <?php foreach ($row as $key => $value):
                        if (!in_array($key, $resultArc2['result']['variables'])) continue;
                        $type = $row[$key . ' type'] ?? null;
                        $dataType = $row[$key . ' datatype'] ?? null;
                        $lang = $row[$key . ' lang'] ?? null;
                        ?>
                        <td>
                            <span class="value-content"<?= $type ? ' data-type="' . $escapeAttr($type) . '"' : '' ?> <?= $lang ? ' lang="' . $escapeAttr($lang) . '"' : '' ?>"><?= $escape($value) ?></span>
                            <?php if ($dataType || $type): ?>
                            <span class="data-type">^^<?= $escape($dataType ?: $type) ?></span>
                            <?php endif; ?>
                            <?php if ($lang): ?>
                            <span class="language">@<?= $escape($lang) ?></span>
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

<?php elseif ($resultArc2): ?>

    <div class="result result-html">
        <h3><?= $escape($translate('Results')) ?></h3>
        <table class="tablesaw tablesaw-stack">
            <thead>
                <tr>
                    <?php foreach ($resultArc2['result']['variables'] as $variable): ?>
                    <th><?= $escape($variable) ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($resultArc2['result']['rows'] as $row): ?>
                <tr>
                    <?php foreach ($row as $key => $value):
                        if (!in_array($key, $resultArc2['result']['variables'])) continue;
                        $type = $row[$key . ' type'] ?? null;
                        $dataType = $row[$key . ' datatype'] ?? null;
                        $lang = $row[$key . ' lang'] ?? null;
                        ?>
                        <td>
                            <?php if ($type && $dataType): ?>
                            <a class="data-type" href="<?= $escapeAttr($dataType) ?>"><?= $escape($type) ?></a>
                            <?php elseif ($type): ?>
                            <span class="data-type"><?= $escape($type) ?></span>
                            <?php endif; ?>
                            <?php if ($lang): ?>
                            <span class="language"><?= $escape($lang) ?></span>
                            <?php endif; ?>
                            <?php if ($type === 'uri' && preg_match($pattern, $value, $matches)): ?>
                            <?php $iri = $matches[1]; ?>
                            <?php $prop = $matches[2]; ?>
                            <?php $prefix = array_search($iri, $namespaces); ?>
                            <a class="value-content" href="<?= $escapeAttr($value) ?>"><?= $escape("$prefix:$prop") ?></a>
                            <?php elseif ($type === 'uri'): ?>
                            <a class="value-content" href="<?= $escapeAttr($value) ?>"><?= $escape($value) ?></a>
                            <?php else: ?>
                            <span class="value-content"<?= $type ? ' data-type="' . $escapeAttr($type) . '"' : '' ?> <?= $lang ? ' lang="' . $escapeAttr($lang) . '"' : '' ?>"><?= $escape($value) ?></span>
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

<?php endif; ?>
